### ISSUE TITLE
Model.afterTokenize event

### ISSUE THREAD

**Issue by LubosRemplik** [UseMuffin/Tokenize#11]
When I generate token on the fly, as per readme

> Finally, if you just wish to create a token on the fly for other custom scenarios (i.e. password-less login), you can manually create a token:
> 
> $this->Users->tokenize($user['id']);

The `Model.afterTokenize` event is not dispatched.

**Comment by ADmad** [comment]
Yes it's not. The idea was that since you are generating token explicitly (instead of auto creation through Model.afterSave event) you can do whatever you want after token creating explicitly too.

I am open to triggering `Model.afterTokenize` after directly calling `tokenize()` too, if you can explain your usecase.

**Comment by LubosRemplik** [comment]
Thanks, makes sense - will trigger manually.
